#!/bin/bash

PROJECT_NAME="${PROJECT_NAME}"
ACCOUNT="${ONBOARDING_ACCOUNT}"
JSON_SA_KEY="${PATH_TO_ONBOARDING_KEY}"
SPIN_SUB_NAME="${ONBOARDING_SUBSCRIPTION}"
GCP_SUB_NAME="${ONBOARDING_SUBSCRIPTION}"

${HALYARD_COMMANDS}
