alias halpush="bash /home/${USER}/halpush.sh"
alias halget="bash /home/${USER}/halget.sh"
alias haldiff="bash /home/${USER}/haldiff.sh"
alias halgcpreset="bash /home/${USER}/resetgcp.sh"
alias kn="kubectl -n spinnaker"
alias k="kubectl"
alias watch="watch "
alias hda="hal deploy apply --wait-for-completion"